"""empty message

Revision ID: 4e5c457bcfd4
Revises: 52febd372f75
Create Date: 2022-08-26 21:19:35.799816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5c457bcfd4'
down_revision = '52febd372f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'people_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('favorites', 'planet_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'planet_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('favorites', 'people_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
